#spring.profiles.active=local
spring.config.import=classpath:application.properties

spring.datasource.url=jdbc:postgresql://localhost:6532/custom_tracker
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver